version: "3.7"
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    container_name: client
    stdin_open: true
    restart: always
    networks:
    - react-express
    depends_on:
    - server
  
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
    - 5001:5001
    stdin_open: true
    environment:
    - GIF_AUTH_KEY=${GIF_AUTH_KEY}  #keeping it open here since we are on a private repo
    - REDIS_URL=${REDIS_URL}  #redis://redis:6379
    - REDIS_PORT=${REDIS_PORT}
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
    - redis
    networks:
    - react-express
    - express-redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
    - express-redis

networks:
  react-express:
  express-redis:
